// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfqzGYxi0xrnBySGWhSAi0vVo3HoypFS8',
    appId: '1:1025239305489:web:23ee37d0ad454b58af90b0',
    messagingSenderId: '1025239305489',
    projectId: 'nightlifepass-66afc',
    authDomain: 'nightlifepass-66afc.firebaseapp.com',
    storageBucket: 'nightlifepass-66afc.firebasestorage.app',
    measurementId: 'G-2REFCXRS12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDQkzMkBjcm59LP-CO2-23YUIzoiJV25g',
    appId: '1:1025239305489:android:9a882714b779540daf90b0',
    messagingSenderId: '1025239305489',
    projectId: 'nightlifepass-66afc',
    storageBucket: 'nightlifepass-66afc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5T7xi6F5F_lAGkT_PIsGb9UxyuQT2NGE',
    appId: '1:1025239305489:ios:6fc78ed69f4c5583af90b0',
    messagingSenderId: '1025239305489',
    projectId: 'nightlifepass-66afc',
    storageBucket: 'nightlifepass-66afc.firebasestorage.app',
    iosClientId: '1025239305489-2aqjg0mhdt2ft1cdqufve3cjkkeefvmm.apps.googleusercontent.com',
    iosBundleId: 'com.proyectolad.nightlifepass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5T7xi6F5F_lAGkT_PIsGb9UxyuQT2NGE',
    appId: '1:1025239305489:ios:6fc78ed69f4c5583af90b0',
    messagingSenderId: '1025239305489',
    projectId: 'nightlifepass-66afc',
    storageBucket: 'nightlifepass-66afc.firebasestorage.app',
    iosClientId: '1025239305489-2aqjg0mhdt2ft1cdqufve3cjkkeefvmm.apps.googleusercontent.com',
    iosBundleId: 'com.proyectolad.nightlifepass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfqzGYxi0xrnBySGWhSAi0vVo3HoypFS8',
    appId: '1:1025239305489:web:8e09da25ff2a391aaf90b0',
    messagingSenderId: '1025239305489',
    projectId: 'nightlifepass-66afc',
    authDomain: 'nightlifepass-66afc.firebaseapp.com',
    storageBucket: 'nightlifepass-66afc.firebasestorage.app',
    measurementId: 'G-G801QLG8Z3',
  );
}
